[workspace]

members = [
    "dcompass",
    "dmatcher",
    "droute",
]

[profile.release]
lto = true
opt-level = 's'
codegen-units = 1

# [patch.crates-io]
# to use async features.
# criterion = { git = "https://github.com/bheisler/criterion.rs", branch = "master" }
