---
verbosity: warn
address: 0.0.0.0:2053

table:
  start:
    if:
      qtype:
        - AAAA
    then:
      # force disable IPv6
      - blackhole
      - end
    else:
      - dispatch_main
  dispatch_main:
    if:
      domain:
        - qname: ytimg.com
        - qname: youtube.com
        - qname: 1e100.net
        - qname: gvt1.com
        - qname: gvt2.com
        - qname: ggpht.com
        - qname: google.com
        - qname: gstatic.com
        - qname: googleapis.com
        - qname: googlevideo.com
        - qname: googleusercontent.com
        - qname: googlesyndication.com
        - qname: g.cn
        - qname: gkecnapps.cn
        - qname: googleapis.cn
        - qname: googlecnapps.cn
        - qname: gstaticcnapps.cn
        - qname: googleadsserving.cn
    then:
      # force all google query with oversea to avoid AS24424
      - query: oversea
      - end
    else:
      - dispatch_secure
  dispatch_secure:
    if:
      domain:
        - file: ../data/blacklist.gz
    then:
      # force all blacklist query with secure to avoid leaking domain to domestic
      - query: secure
      - end
    else:
      - dispatch_final
  dispatch_final:
    if: any
    then:
      # finally, query rest domain from domestic and check_secure, works like chinadns
      - query: domestic
      - check_secure
  check_secure:
    if:
      # geoip:
      #   codes:
      #     - CN
      ipcidr:
        - ../data/ipcn.txt.gz
    else:
      - query: secure
      - end

upstreams:
  dnspodDoH:
    https:
      no_sni: false
      name: doh.pub
      addr: 162.14.21.56:443

  aliDoH:
    https:
      no_sni: false
      name: dns.alidns.com
      addr: 223.5.5.5:443

  dnspodDoT:
    tls:
      no_sni: false
      name: dot.pub
      addr: 162.14.21.178:853

  aliDoT:
    tls:
      no_sni: false
      name: dns.alidns.com
      addr: 223.6.6.6:853

  googleDoH:
    https:
      no_sni: true
      name: dns.google
      addr: 8.8.4.4:443

  quad9DoH:
    https:
      no_sni: true
      name: dns.quad9.net
      addr: 149.112.112.112:443

  cloudflareDoH:
    https:
      no_sni: true
      name: cloudflare-dns.com
      addr: 162.159.36.1:443

  googleDoT:
    tls:
      no_sni: true
      name: dns.google
      addr: 8.8.8.8:853

  quad9DoT:
    tls:
      no_sni: true
      name: dns11.quad9.net
      addr: 9.9.9.11:853

  cloudflareDoT:
    tls:
      no_sni: true
      name: cloudflare-dns.com
      addr: 1.1.1.1:853

  opendnsDoH:
    https:
      no_sni: true
      name: doh.opendns.com
      addr: 146.112.41.2:443

  adguardDoH:
    https:
      no_sni: true
      name: dns.adguard.com
      addr: 94.140.15.15:443

  adguardDoT:
    tls:
      no_sni: true
      name: dns.adguard.com
      addr: 94.140.14.14:853

  # quad101DoH:
  #   https:
  #     no_sni: true
  #     name: dns.twnic.tw
  #     addr: 101.102.103.104:443

  # quad101DoT:
  #   tls:
  #     no_sni: true
  #     name: dns.twnic.tw
  #     addr: 101.101.101.101:853

  # ------------ FINAL -------------

  domestic:
    hybrid:
      - dnspodDoH
      - aliDoH
      - dnspodDoT
      - aliDoT

  secure:
    hybrid:
      - googleDoH
      - quad9DoH
      - cloudflareDoH
      - googleDoT
      - quad9DoT
      - cloudflareDoT
      - opendnsDoH
      - adguardDoH
      - adguardDoT
      # - quad101DoH
      # - quad101DoT

  oversea:
    hybrid:
      - opendnsDoH
      - adguardDoH
      - adguardDoT
      # - quad101DoH
      # - quad101DoT
