---
verbosity: "off"
address: 0.0.0.0:2053
table:
  start:
    if:
      domain:
        - gzip: "../data/china.gz"
    then:
      - query: domestic
      - end
    else:
      - query: secure
      - end
upstreams:
  domestic:
    udp:
      addr: 114.114.114.114:53
      timeout: 1
  secure:
    https:
      timeout: 2
      no_sni: false
      name: dns.quad9.net
      addr: 9.9.9.9:443
