---
verbosity: 'off'
cache_size: 4096
address: 0.0.0.0:2053
table:
- tag: start
  if:
    ipcidr:
      path:
        - ../data/ipcn.txt
      on: src
  then:
  -
    - query: domestic
  - end
  else:
  -
    - query: secure
  - end
upstreams:
- method:
    udp:
      addr: 114.114.114.114:53
      timeout: 1
  tag: domestic
- timeout: 2
  method:
    https:
      no_sni: false
      name: dns.quad9.net
      addr: 9.9.9.9:443
  tag: secure
